DeveloperOrg/force-app/main/default/objects/Student__c/Student__c.object-meta.xml
<CustomObject>
    <description>Custom object for the students</description>
    <label>Student</label>
    <nameField>
        <label>Student Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Students</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

DeveloperOrg/force-app/main/default/objects/Student__c/fields/Fees_Paid__c.field-meta.xml
<CustomField>
    <fullName>Fees_Paid__c</fullName>
    <label>Fees Paid</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Fees_Paid</valueSetName>
    </valueSet>
</CustomField>

DeveloperOrg/force-app/main/default/objects/Student__c/recordTypes/STudent.recordType-meta.xml
<RecordType>
    <fullName>STudent</fullName>
    <active>true</active>
    <label>STudent</label>
</RecordType>

DeveloperOrg/force-app/main/default/classes/DemoSobjects.cls
public class DemoSobjects {
    
    public void demoMethod()
    {
        //Standard Object call
        Account acc = new Account();
        acc.Name = 'Babu Rao ganpat rao apte';
        acc.Phone = '123466789';
        System.debug('acc Print =>'+acc);
        
        
        // Custom object call
        Student__C std = new Student__c();
        std.Name = 'Test';
        std.Fees_Paid__c = 'Yes' ;
        System.debug('std Print =>'+std);
        
        // Generic object call
        Sobject obj;
        obj = new Account( Name = 'Tes', Phone = '1234567897');
        Account accgeneric = (Account)obj;
        System.debug('accgeneric Print =>'+accgeneric);
        obj = new Student__C( Name = 'Student test');
        Student__C stdgeneric = (Student__C)obj;
        System.debug('stdgeneric Print =>'+stdgeneric);
        
        //Using in Loop  
        List<Account> accc = new List<Account>();
     //   accc = [Select Id, Name from Account Limit 2];
       // System.debug('first before loop'+accc);
        
        Set<Id> accids = new Set<Id>();
        Map<Id, Account > mapLists = new Map<Id, Account>( [Select Id, Name From account Limit 2]);
        //Using List Loop first option using Is EMpty method and if else with for loop
     //   if(!accc.isEmpty())
     //   {
           // for(Account accloop : accc) // Use of SOQL
        for(Account accloop : [Select Id, Name from Account Limit 2])
        {
            accids.add(accloop.Id);    
        }
        
        if(! accids.isEmpty())
        {
            //for( id i : accids)
            for ( id i : mapLists.keySet())
            {
                if(mapLists.containsKey(i))
                {
                    System.debug('map Value =>'+mapLists.get(i));
                }
               // System.debug('i =>'+i); 
            }
        }
            //System.debug('accids =>'+accids);   
        //}
       // else
        //{
        //    System.debug('list is empty =>');  
        //} 
    }
}